#!/usr/bin/zsh
# $XDG_CONFIG_HOME/zsh/zshenv
################################################################################
# ------------------------------------------------------------------------------
# file: ~/.config/zsh/zshenv
# author: Pedro Maltez - http://github.com/pedromaltez/dotfiles
# last modified: 4/11/2014 - 4:36 UTC
# ------------------------------------------------------------------------------
################################################################################

for file in $ZDOTDIR/zshenv.d/**/*.zsh; do
  source $file
done

echo "Loaded zshenv"
# ------------------------------------------------------------------------------
# Overrides go here!
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Anything that I want to test out should just go in this section so that it's
# easy to find and change or delete
# ------------------------------------------------------------------------------

